#!/bin/bash

# BREW!
#/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
#git -C "$(brew --repo homebrew/core)" fetch --unshallow

# comms
#brew cask install slack
#brew cask install zoomus
#brew cask install discord
#brew cask install telegram

# docker
brew cask install docker
brew install docker-compose

# programming
brew install neovim wget zsh cmake
brew install cask zsh-autosuggestions
brew install python3
pip3 install neovim
curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
brew cask install kitty

# zsh shell staff
brew tap caskroom/fonts
brew cask install font-hack-nerd-font
git clone https://github.com/bhilburn/powerlevel9k.git ~/.oh-my-zsh/custom/themes/powerlevel9k
sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
git clone https://github.com/ryanoasis/nerd-fonts.git
cd nerd-fonts && ./install && cd .. && rm -rf nerd-fonts

# utility
#brew cask install dropbox
brew cask install authy
brew cask install alfred
brew cask install bettertouchtool
brew install the_silver_searcher
brew cask install balenaetcher

# crypto
brew cask install ledger-live

brew cask install signal

# tmux
brew install tmux reattach-to-user-namespace

brew install gpg
brew install tldr

brew install lsd

# show hidden files
defaults write com.apple.finder AppleShowAllFiles TRUE
killall Finder
